### ISSUE TITLE
result  filter

### ISSUE THREAD

**Issue by ucassee** [ebi-pf-team/interproscan#129]
I used interproscan  to annotate my metagenome. But  for each genes, it may have more than one annotation(as follow).

```
B9T3L8_NODE1277_8	dfecf7b04bbb27e31fb1b6d0346acd3b	767	Pfam	PF01590	GAF domain	208	344	1.3E-20	T	20-11-2019	IPR003018	GAF domain	GO:0005515	
B9T3L8_NODE1277_8	dfecf7b04bbb27e31fb1b6d0346acd3b	767	Pfam	PF01590	GAF domain	42	177	2.6E-19	T	20-11-2019	IPR003018	GAF domain	GO:0005515	
B9T3L8_NODE1277_8	dfecf7b04bbb27e31fb1b6d0346acd3b	767	TIGRFAM	TIGR00229	sensory_box: PAS domain S-box protein	361	477	2.8E-8	T	20-11-2019	IPR000014	PAS domain		
B9T3L8_NODE1277_8	dfecf7b04bbb27e31fb1b6d0346acd3b	767	Pfam	PF00211	Adenylate and Guanylate cyclase catalytic domain	511	686	3.1E-34	T	20-11-2019	IPR001054	Adenylyl cyclase class-3/4/guanylyl cyclase	GO:0009190|GO:0035556	
B9T3L8_NODE1277_8	dfecf7b04bbb27e31fb1b6d0346acd3b	767	Pfam	PF00989	PAS fold	361	471	5.5E-10	T	20-11-2019	IPR013767	PAS fold	GO:0006355
```	

So  I want to know should I filter them by e-value or keep them all.
Thanks in advance

**Comment by gsn7** [comment]
You should keep them all. 
If you want to filter, you may want to check if an match has  an InterPro accession e.g. IPR013767 associated with it. If it has, it means it has passed additional quality checks (manually done by curators) and is very unlikely to be a false match annotation

**Comment by ucassee** [comment]
Thanks for your reply
But I feel confused why a gene could have many different functions. As I mention in the first response, `B9T3L8_NODE1277_8`  have three different InterPro accessions `IPR003018,IPR000014,IPR013767`. Which should I keep?

**Comment by happy-lorna** [comment]
There are a couple of reasons why a single sequence may have multiple InterPro annotations. 

1. These annotations are of type domain. A single protein may contain multiple domains, each of which may have a specific individual function. The combination of these domain functions contributes to the overall function of the protein. As such, it is very normal for a full-length protein sequence to potentially match a type family entry, and/or any number of type domain (and/or type site) entries.

2. InterPro entries exist in hierarchies, with each child entry representing a more specific set of protein matches than its parent. These can be more specific in terms of function, or in terms of taxonomy. Due to this, we would expect any sequence which matches a child model to also match its parent model. This is what you are seeing in the case of your matches to IPR000014 and IPR013767.

Hope this helps.

**Comment by ucassee** [comment]
@happy-lorna @gsn7  Thanks for your patience~
I got it and will keep all the annotations for the further analysis
