### ISSUE TITLE
Missing <protein> tag in the generated xml file output

### ISSUE THREAD

**Issue by atiweb** [ebi-pf-team/interproscan#135]
Im having some missing tags in the generated xml file output. Especifically some` <protein>` tag. Someone else is having the same issue?
Using InterProScan-5.39-77.0 in standalone mode.

**Comment by gsn7** [comment]
can you give more details: the xml part as well as the input protein sequence

**Comment by atiweb** [comment]
Yes, of course.
For example, in all generated iprscan.xml, in the beginning of file should be:
************************
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5">
<protein>
    <sequence md5="a1059ab7d6f2c12601014893a24dd0a5">...</sequence>
    <xref id="5z489_004620-T1" name="5z489_004620-T1 5z489_004620"/>
    <matches>
*************************
And is coming up:
*************************
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5">
    <sequence md5="a1059ab7d6f2c12601014893a24dd0a5">...</sequence>
    <xref id="5z489_004620-T1" name="5z489_004620-T1 5z489_004620"/>
    <matches>
*************************
The <protein> tag is missing, that is happening  in all execution.
Then more ahead the same tag is missing randomly, but the closing tag </protein> exist, only the opening tag <protein> is missing.


This is one of the proteins file processed:
[genome.proteins.fasta.tar.gz](https://github.com/ebi-pf-team/interproscan/files/4214076/genome.proteins.fasta.tar.gz)

Im running right now. Will upload when finished the full iprscan.xml generated file for analysis;
Thank you.

**Comment by gsn7** [comment]
your xml output format is wrong. the InterProScan output expected should have the following header
`<?xml version="1.0" encoding="UTF-8"?><protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5" interProScanVersion="5.39-77.0">`

your problem is not generated by InterProScan. I have run your input using InterProScan-5.39-77.0 and gotten correct xml output. All the '<protein>' tags are there. So my guess is that you are not running InterProScan natively, but through some other third party software that is mangling the xml output.

We have run InterProScan-5.39-77.0 on more than 300 millions protein sequences and have not had this problem.
Can you send me the command you run?

**Comment by atiweb** [comment]
Yes @gsn7, you are right, is not a IPRscan problem, is of funannotate, The problem is addressed here: https://github.com/nextgenusfs/funannotate/issues/362.
Thank by your time and attention, very grateful.
