### ISSUE TITLE
InstallationRequirements 5.41-78.0: says Java 11 or higher, but it asks for 11 if Java 13 is available

### ISSUE THREAD

**Issue by ckeeling** [ebi-pf-team/interproscan#138]
Trying to freshly install and get interproscan 5.41-78.0 working:

```bash
java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

./interproscan.sh -i test_proteins.fasta -f tsv
Java version 11 is required to run InterProScan.
Detected version 13.0.1
Please install the correct version.
```

I see that line 35 of interproscan.sh specifically checks if major version ne 11, not lt 11. If I change this line to lt, it passes this test, but I then find that the lookup service doesn't match this version. Instead, it is SERVER:5.39-77.0. 

```
...
The version of InterProScan you are using is 5.41-78.0
The version of the lookup service you are using is 5.39-77.0
As the data in these versions is not the same, you cannot use this match lookup service.
...
```

It seems that the lookup service has not been updated to match your very recent release of InterProScan 5.41-78.0.

**Comment by gsn7** [comment]
yes, the check looks for major java version 11. we will change that and test it on all the higher java versions.
the lookup match service for release 5.41-78.0 is not ready, and it will not be ready soon. Its taking a longer time than usual to build the lookup match database due to database performance problems and other issues. so you may want to disable the lookup using '--disable-precalc' option.

**Comment by ckeeling** [comment]
Thanks!
