### ISSUE TITLE
ERROR StatusLogger No Log4j 2 configuration file found

### ISSUE THREAD

**Issue by WellJoea** [ebi-pf-team/interproscan#150]
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2

Must  the Log4j 2 be configured ?

**Comment by gsn7** [comment]
when do you get this error?

**Comment by larssnip** [comment]
I get a similar error. I am running interproscan using singularity and the container at https://agbase-docs.readthedocs.io/en/latest/interproscan/using_iprs_cmd.html

The logfile ends with:
log4j:WARN No appenders could be found for logger (org.apache.activemq.broker.BrokerService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
head: cannot open '/data/annotations/query.0.xml' for reading: No such file or directory

There are 4500 predicted proteins, and these are split into 5 chunks (1000 x 4 and 500), but only results for the last chunk ends up in the gff3 file.

**Comment by matthiasblum** [comment]
Hi @cymon 

Did InterProScan report results? Have you tried to [Docker image](https://hub.docker.com/r/interpro/interproscan)?

**Comment by cymon** [comment]
Hi @matthiasblum, well no, but not for any reason related to log4j I think: I'm using a custom [Docker image](https://hub.docker.com/repository/docker/cymon/interproscan-5.64-96.0/general) as I'm trying to update this [workflow](https://github.com/emo-bon/MetaGOflow) to InterProScan-5.64-96.0 using the *V3.noaf Prosite binaries so that it'll run on our AMD EPYC cluster... let's just say that I'm having some problems...

If there is a InterProScan-5.64-96.0 image configured to use those *V3.noaf Prosite binaries I'd be v. interested...
