### ISSUE TITLE
ERROR: uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep 

### ISSUE THREAD

**Issue by Tdanis** [ebi-pf-team/interproscan#154]
Hello , I am a new user if interproscan 5 and after my first run I took errors which are in atteched file
[inpro_output.TXT](https://github.com/ebi-pf-team/interproscan/files/4805178/inpro_output.TXT)

my command is :

interproscan.sh -i $work_dir/file4.fa -cpu 20 -t p -dp -pa --goterms --iprlookup

(I run interproscan in hpc cluster)

could you help me please ? 

Thank you

**Comment by gsn7** [comment]
on what linux distribution are you running InterProScan?
it is likely the problem is libdw and if you are on ubuntu or any system that uses apt, you can install libdw as follows:
sudo apt install libdw1 libdw-dev
or on centos/redhat
yum install libdw1 libdw-dev

after installing libdw, check if you get any errors by running:
./interproscan.sh -i test_all_appl.fasta -dp
