### ISSUE TITLE
InterProScan-5.47-82.0 gets stuck

### ISSUE THREAD

**Issue by zeynepkurtw** [ebi-pf-team/interproscan#167]
Hi,

I'm trying to run InterProScan-5.47-82.0 on a novel genome with around 100.000 genes (file size is 30 M). But the software gets stuck at the uploading sequences step. I've run it a few times and I still have the same problem. In the other comments regarding similar issues, It has been said that the memory issue is solved on the latest version. Do you think splitting the input file into small batches would work and the output would be fine?

The command line I've used is the following:

`interproscan.sh -cpu 32 -f tsv,html -goterms -i HIN_101051.faa -iprlookup --pathways -d interproscan `

There is no error, the software just crashes after giving this output ( in the previous runs I've had the last line repeated several times) :

> Matches for any sequences that are not represented in the lookup service will be calculated locally.
13/10/2020 09:34:49:382 Uploaded 82888 unique sequences for analysis
13/10/2020 09:35:47:383 37% completed
13/10/2020 09:35:48:550 87% completed

Any help would be appreciated!

**Comment by gsn7** [comment]
there have been memory improvements, but with 32 cpu cores, 100.000 genes would still require a lot of memory as they have to be translated to ORFs/proteins. You don't mention how much memory you reserve for you job? Memory is also a big factor on how you split your input.

I would suggest, you split your input into say 10 files and use 16 cpu cores for each run. This will be more tractable. Additionally, you may want to add the json output format so that you can use our upcoming feature where you can visualise your results using our new graphic frameworks as the current html output format is outdated.

let us know how this works out.

**Comment by zeynepkurtw** [comment]
Thank you for your quick response!

The computer I'm using has 126G memory but I'vent set up any parameters for the memory usage. Regarding splitting files, do you mean using 16 CPUs in parallel on those inputs?

**Comment by zeynepkurtw** [comment]
No, my input sequences are proteins so it's fine. I should've mentioned that too, but Thank you!!
