### ISSUE TITLE
Analysis ProDom does not exist or is deactivated

### ISSUE THREAD

**Issue by bioone** [ebi-pf-team/interproscan#169]
My interproscan version is InterProScan-5.47-82.0. When i was running this software with 
`./interproscan.sh -appl CDD,COILS,Gene3D,HAMAP,MobiDBLite,PANTHER,Pfam,PIRSF,PRINTS,ProDom,PROSITEPATTERNS,PROSITEPROFILES,SFLD,SMART,SUPERFAMILY,TIGRFAM -i /path/to/sequences.fasta`
Log file said "Analysis ProDom does not exist or is deactivated."
I want to know if this software contain this database?

**Comment by gsn7** [comment]
ProDom is removed from InterPro since May 2019 and hence also removed from InterProScan. There are no annotations lost as a results of this. This is due to the fact that the other databases do cover all the annotations you would get from ProDom

if you run `./interproscan.sh -help` you get the analyses available for your installtion.

**Comment by duboism** [comment]
If I'm correct, `ProDom` is still listed in the doc ([here](https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html#included-analyses) and [here](https://interproscan-docs.readthedocs.io/en/5.48-83.0/HowToRun.html#included-analyses)).

**Comment by duboism** [comment]
`ProDom` has been removed from the doc by ebi-pf-team/interproscan-docs@e740410.
