### ISSUE TITLE
activating TMHMM and SignalP

### ISSUE THREAD

**Issue by JanVHenkel** [ebi-pf-team/interproscan#170]
Hey!

I just got the licence and files for SignalP 4.1 and TMHMM 2.0 (the ones mentioned by ./interproscan.sh as not activated. I copied the tar.gz into the folder where interproscan.sh is located and unpacked them. As i am very unexperienced with the UNIX system, I do not know how to proceed afterwards. I dont understand the explanations given in:
https://interproscan5-docs.readthedocs.io/en/latest/ActivatingLicensedAnalyses.html

cheers,
Jan

**Comment by gsn7** [comment]
We will update the documentation to make it more clear. btw use the link https://interproscan-docs.readthedocs.io/ for help as opposed to the one you used.

Running `./interproscan.sh -help` will show you if the files have been copied to the right places.
If not, then make sure you do the following where <interproscan-install-dir> is the path to where you have installed interproscan:

For SignalP:
asumming your  unzipped signalp files are in directory **signalp-4.1**, then copy the whole directory into the interproscan bin directory  as follows  
`cp -r signalp-4.1  /<interproscan-install-dir>/bin/signalp/4.1`

For TMHMM:
`cp tmhmm-2.0c/bin/* bin/tmhmm/2.0c/
cp tmhmm-2.0c/lib/TMHMM2.0.model /<interproscan-install-dir>/data/tmhmm/2.0c/`

then run  `./interproscan.sh -help` to see if all files inthe right places.

Did you consider using Phobius (https://interproscan5-docs.readthedocs.io/en/latest/ActivatingLicensedAnalyses.html#phobius) instead of TMHMM for transmembrane prediction? Phobius is better at all types of predictions.

**Comment by JanVHenkel** [comment]
Thank you very much for your help, with your instructions i managed to install SignalP and Phobius! Have a nice day!
