### ISSUE TITLE
Failing to connect to online services and OOM errors

### ISSUE THREAD

**Issue by Lamm-a** [ebi-pf-team/interproscan#193]
I am trying to run InterProScan on pooled metagenome assemblies but am running into some issues. 

**Version**
v5.50-84.0

*The environment*:
We use environment modules
2) anaconda3/4.4.0   3) openjdk/15.0.1   4) perl/5.30.2   5) interproscan/5.50-84.0

**Connection to pre-calculated match lookup**

It seems I am unable to connect to your online service, as the `STDOUT `suggests this could be due to firewalls or a proxy issue, how do i check if it is either of these?

The tool then goes on to locally analyse the assemblies bu seems to rum into out of memory errors:
```
16:19:25.327 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Out of memory.; SQL statement:
select parameters0_.step_instance_id as step_ins1_106_0_, parameters0_.parameters as paramete2_106_0_, parameters0_.parameters_key as paramete3_0_ from public.step_instance_parameters parameters0_ where parameters0_.step_instance_id=? [90108-199]
16:19:25.329 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - The database has been closed [90098-199]
16:19:25.329 [main] ERROR org.springframework.transaction.interceptor.TransactionInterceptor - Application exception overridden by rollback exception
```
Here is the whole `STDOUT ` and `STDERR `log files respectively:
[interproscan-call.sh.o31182877.zip](https://github.com/ebi-pf-team/interproscan/files/6163169/interproscan-call.sh.o31182877.zip)

[interproscan-call.sh.e31182877.zip](https://github.com/ebi-pf-team/interproscan/files/6163204/interproscan-call.sh.e31182877.zip)

My input command is as follows:
`interproscan.sh -tempdir $outdir -t p -i $input -d $outdir -f TSV, HTML, JSON -cpu 16`

I am allotting `100gb` of memory and `16` cores

Would you recommend I allot more memory or splitting the metagenomes into smaller sizes?

A run on another metagenome also ram into OOM issues but a different one as far as I can see. Again here is the `STDOUT `and `STDERR ` respectively:

[interproscan-call.sh.o31182876.zip](https://github.com/ebi-pf-team/interproscan/files/6163216/interproscan-call.sh.o31182876.zip)
[interproscan-call.sh.e31182876.zip](https://github.com/ebi-pf-team/interproscan/files/6163217/interproscan-call.sh.e31182876.zip)

**Comment by gsn7** [comment]
The size of your input is too big and there are more errors you may encounter if optimisations are not done.
1. follow the instructions under known issues - issue 1 (https://interproscan-docs.readthedocs.io/en/latest/KnownIssues.html#error-after-more-than-90-completed). 
2. increase the max heap space (-Xmx)  in inteproscan.sh to something like -Xmx32000M
3. split your input into smaller chunks say 160,000 sequences and reduce the memory allocated to say 36GB. 
4. Since your input is from metagenomes, you will not benefit performance improvement in using the pre-calculated match lookup, so add `'-dp'` option to the interproscan command
5. after making these changes also let me know if are able to run the test commands:
     `./interproscan.sh -i test_all_appl.fasta -f tsv -dp`     
     `./interproscan.sh -i test_all_appl.fasta -f tsv`

and in general with metagenomes, add `'-dp'` option, which disables connecting to our pre-calculated match lookup server.

**Comment by gsn7** [comment]
the new version v5.51-85.0 should allow for larger set of input  sequences > 320,000   with the adjustment of the  max heap space (-Xmx) setting
