### ISSUE TITLE
Conda Install - errors when running test data

### ISSUE THREAD

**Issue by hans-vg** [ebi-pf-team/interproscan#232]
I just completed the conda install of Interproscan. After installation, I downloaded and uncompressed the tar.gz data folder.  Since this was a conda install, I wasn't sure if I needed to run the initial_setup.py (I couldn't find it in the conda directories).

When I ran the test_all_app.fasta alignment, I found the indexes weren't working properly.

```
interproscan.sh -i /data/gpfs/home/hvasquezgross/mambaforge/envs/interproscan/share/InterProScan/test_all_appl.fasta -f tsv -dp
Checking any hmm models that need indexing ... this may take a few minutes
Working...    SSI index construction failed:
  primary keys not unique: '7,8-didemethyl-8-hydroxy-5-de' occurs more than once
Working...    SSI index construction failed:
  secondary keys not unique: '100879' occurs more than once
Completed indexing the hmm models.
25/10/2021 13:16:47:888 Welcome to InterProScan-5.52-86.0
25/10/2021 13:16:47:893 Running InterProScan v5 in STANDALONE mode... on Linux
25/10/2021 13:16:53:390 RunID: login-1_20211025_131653206_ausz
25/10/2021 13:17:01:456 Loading file /data/gpfs/home/hvasquezgross/mambaforge/envs/interproscan/share/InterProScan/test_all_appl.fasta
25/10/2021 13:17:01:458 Running the following analyses:
[CDD-3.18,Coils-2.2.1,Gene3D-4.3.0,Hamap-2020_05,MobiDBLite-2.0,Pfam-33.1,PIRSF-3.10,PIRSR-2021_02,PRINTS-42.0,ProSitePatterns-2021_01,ProSiteProfiles-2021_01,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2021-10-25 13:17:07,266 [amqEmbeddedWorkerJmsContainer-5] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1
Command: hmmscan -E 10 -Z 15438 --cpu 1 -o /data/gpfs/home/hvasquezgross/temp/login-1_20211025_131653206_ausz//jobSuperFamily-1.75/000000000001_000000000005.raw.out data/superfamily/1.75/hmmlib_1.75 /data/gpfs/home/hvasquezgross/temp/login-1_20211025_131653206_ausz//jobSuperFamily-1.75/000000000001_000000000005.fasta
Error output from binary:

Error: Failed to open binary auxfiles for data/superfamily/1.75/hmmlib_1.75: use hmmpress first
```

After finding a related Github Issue, I was able to find that Interproscan recipe installs hmmpress from 3.3, 3.1b1, and 3.0b2. By default, interproscan runs the 3.3 hmmpress which is failing. I manually ran the hmmpress from 3.1b1 and was successfully able to complete that step. 

`
bin/hmmer/hmmer3/3.1b1/hmmpress data/superfamily/1.75/hmmlib_1.75 
`

When I reran the test data, I still get an error, but it looks like it completed.
```
interproscan.sh -i /data/gpfs/home/hvasquezgross/mambaforge/envs/interproscan/share/InterProScan/test_all_appl.fasta -f tsv -dp
Checking any hmm models that need indexing ... this may take a few minutes
Working...    SSI index construction failed:
  primary keys not unique: '7,8-didemethyl-8-hydroxy-5-de' occurs more than once
Completed indexing the hmm models.
25/10/2021 13:29:45:735 Welcome to InterProScan-5.52-86.0
25/10/2021 13:29:45:739 Running InterProScan v5 in STANDALONE mode... on Linux
25/10/2021 13:29:51:279 RunID: login-1_20211025_132951095_3gyf
25/10/2021 13:29:58:932 Loading file /data/gpfs/home/hvasquezgross/mambaforge/envs/interproscan/share/InterProScan/test_all_appl.fasta
25/10/2021 13:29:58:934 Running the following analyses:
[CDD-3.18,Coils-2.2.1,Gene3D-4.3.0,Hamap-2020_05,MobiDBLite-2.0,Pfam-33.1,PIRSF-3.10,PIRSR-2021_02,PRINTS-42.0,ProSitePatterns-2021_01,ProSiteProfiles-2021_01,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
25/10/2021 13:30:17:692 25% completed
25/10/2021 13:30:35:865 52% completed
25/10/2021 13:30:49:079 76% completed
25/10/2021 13:31:06:652 90% completed
25/10/2021 13:31:25:408 100% done:  InterProScan analyses completed

2021-10-25 13:31:25,917 [main] [uk.ac.ebi.interpro.scan.jms.main.Run:1883] WARN - deleteWorkingDirectoryOnCompletion : false
```
Can this error be safely ignored? If not, which file should I try hmmpress to fix this error?

**Comment by abretaud** [comment]
I can confirm there's a problem with 2 hmm dbs:
- data/sfld/4/sfld.hmm contains a duplicate `7,8-didemethyl-8-hydroxy-5-de` entry
- data/superfamily/1.75/hmmlib_1.75 contains several duplicates of `100879` entry

(the entries have the same `ACC` but their content is not identical from what I can see)

It's the same with releases 5.52-86.0 and the new 5.53-87.0

The problem is *revealed* by conda using hmmer/hmmpress 3.3.2 only to index all hmm dbs, but I guess it can give strange results if the problem is just ignored by using an older hmmpress version.

Any clue on what could be done here? Would it be possible to fix the duplications in the db files themselves? If someone here is in contact with the authors of these db, maybe we could ask them to fix it directly in their release?

**Comment by LeeBergstrand** [comment]
I am also running into the exact same issue.

**Comment by LeeBergstrand** [comment]
@abretaud The problem is revealed by conda using hmmer/hmmpress 3.3.2 only to index all hmm dbs, but I guess it can give strange results if the problem is just ignored by using an older hmmpress version.

Which version of HMMPRESS still works without errors?

**Comment by LeeBergstrand** [comment]
@abretaud I'm pretty sure the EBI uniprot team is in charge of all these database now. My understanding is that they all get moved under the uniprot team's maintance after the original authors can no longer maintain the DB.

**Comment by abretaud** [comment]
From my tests, the change in hmmpress happened in version 3.2. I've found this in the changelog which looks related: https://github.com/EddyRivasLab/hmmer/blob/master/release-notes/RELEASE-3.2#L39

I don't know who from EBI InterPro team we could ping?

**Comment by LeeBergstrand** [comment]
@abretaud I think you could contact @rdfinn who is the PI of InterPro: https://scholar.google.com/citations?user=G-43AGgAAAAJ

**Comment by matthiasblum** [comment]
Hi, and sorry for not replying sooner.

@LeeBergstrand Rob Finn used to be in charge of InterPro, but the current PI is Alex Bateman.

Because SFLD and SUPERFAMILY profile databases contain duplicated keys, the initial script (`initial_setup.py`) uses an older version of `hmmer`.

Usually, we try to avoid altering files created by external resources (e.g. HMM files). However, since the affected files are old, it may possible to edit them and distribute them with InterProScan so it would be possible to use a more recent version of `hmmer`. I will check and I will update this issue.

**Comment by Lsz-20** [comment]
@hans-vg Have you solved this question?I alos install interproscan=5.54 via conda and the same warn:
[main] [uk.ac.ebi.interpro.scan.jms.main.Run:1883] WARN - deleteWorkingDirectoryOnCompletion : false
As @matthiasblum mentioned, i have tryed hmmer=3.3.2--->3.1b, but it also can't work well and show me the same question

**Comment by moskalenko** [comment]
Using an older version of hmmpress is no longer a valid option since interproscan 5.60 depends on and runs hmmscan 3.3, which errors out with

Error: bad format, binary auxfiles, data/superfamily/1.75/hmmlib_1.75:
binary auxfiles are in an outdated HMMER format (3/b); please hmmpress your HMM file again
