### ISSUE TITLE
I have a problem with log4j 

### ISSUE THREAD

**Issue by vini8cs** [ebi-pf-team/interproscan#302]
Here is the error I get when trying to run InterProScan:

19/01/2023 14:59:10:739 Welcome to InterProScan-5.60-92.0
19/01/2023 14:59:10:739 Running InterProScan v5 in STANDALONE mode... on Linux
log4j:WARN No appenders could be found for logger (org.apache.activemq.broker.BrokerService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Could not write to temporary directory: /home/data/vinicius/Sabrina_dados_urgentes/SRR13426335/temp

The page http://logging.apache.org/log4j/1.2/faq.html#noconfig doesn't seem to answer my questions, so I've been trying to figure out what else to do.

**Comment by matthiasblum** [comment]
Hi,

I think InterProScan stops not because of log4j, but because of it cannot create the run's temporary directory (`Could not write to temporary directory` in your log).

Does the user running InterProScan have the right to create a directory in `/home/data/vinicius/Sabrina_dados_urgentes/SRR13426335`?
