### ISSUE TITLE
SSI index construction failed: primary keys not unique (conda installation)

### ISSUE THREAD

**Issue by pmjklemm** [ebi-pf-team/interproscan#305]
For people, that encountering #280 / #232 in 2023 using the conda installation of interproscan.
Version: HMMER 3.3.2 as the conda dependancy gods specified for the latest interproscan version major=5.59 minor=91.0

I had the problem with primary as well as some secondary keys:
```
SSI index construction failed:
  primary keys not unique: '7,8-didemethyl-8-hydroxy-5-de' occurs more than once
...
```

My corrupted files are data/sfld/4/sfld.hmm and data/superfamily/1.75/hmmlib_1.75 (found with `find data/ -type f | xargs grep -n "7,8-didemethyl-8-hydroxy-5-de" | head` ...)

Here is my script fixing the problems:
```
for f in data/sfld/*/sfld.hmm data/superfamily/*/hmmlib_*[0-9]; do
cp $f $f.bak;
perl -lne '$_=~s/[\s\n]+$//g;if(/^(NAME|ACC) +(.*)$/){if(exists $d{$2}){$d{$2}+=1;$_.="-$d{$2}"}else{$d{$2}=0;}}print "$_"' $f > $f.tmp; mv $f.tmp $f;
done
```
then call the setup script again and it works like a charm

**Comment by andradejon** [comment]
Yup! Worked like a charm! Trying to get this software to work has been a true test of patience.

I will also add that the interproscan.properties file designates specific versions of the hmm libraries when setting paths, so trying to run it with newer libraries will also give errors. For example the version of interproscan that comes with the conda install is 5.50-88.0, and in the properties file it looks for CDD-3.18, Hamap-2020_05, Panther-15.0, Pfam-34.0, and ProSitePatterns-2021_01, but version of libraries I downloaded (5.60-92.0) doesn't include those. I just changed the name of those folders to the earlier ones to try and trick interproscan, and hmmpress was able to index them so it seems like that worked. It's a pretty clunky solution though, so I just ended up downloading the 5.50-88.0 libraries, which eliminated that specific issue anyway.

While I'm here (not sure proper etiquette in commenting on separate issues in a thread), I also have been having other issues with interproscan running prosite.
First of all, the properties file doesn't direct properly to ps_scan.pl. Trying to run interproscan gives:
"Cannot run program "ps_scan.pl": error=2, No such file or directory"
Going into the properties file and changing "binary.prosite.psscan.pl.path=ps_scan.pl" to "binary.prosite.psscan.pl.path=${bin.directory}/prosite/ps_scan.pl" fixes that problem.

Second of all, pfscanV3 and pfsearchV3 throw errors saying "inappropriate ioctl for device" which I haven't quite made sense of. See #215 for this, and #251 might have been having a similar issue. Making these changes fixes it partially:
binary.prosite.pfscanv3.path=${bin.directory}/prosite/pfscanV3
binary.prosite.pfsearchv3.path=${bin.directory}/prosite/pfsearchV3
binary.pfscanv3.path=${bin.directory}/prosite/pfscanV3
binary.pfsearchv3.path=${bin.directory}/prosite/pfsearchV3

But then I still get an "Error setting affinity!" message which seems to be an issue if you're running on a cluster like I am. According to sib-swiss/pftools#25 and sib-swiss/pftools#20, pftools isn't compiled in the conda build using -DUSE-AFFINITY=OFF so there's some issue with how many cores pfsearchV3 and pfscanV3 try to use. Downloading and compiling these directly and then putting them in the bin of your interproscan environment seems to fix this. 

Here's my entire installation workflow, which at least seems to work on the provided test data:

#set up your environment and variables setting which versions of things you want
mkdir interproscan
cd interproscan
conda create -y -n interproscan
conda activate interproscan
conda install -y -c bioconda interproscan
conda list -n interproscan
major_version=5.55
minor_version=88.0
pftools_version=3.2.12

#download everything you need, which will take some time
wget http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${major_version}-${minor_version}/interproscan-${major_version}-${minor_version}-64-bit.tar.gz.md5
wget http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${major_version}-${minor_version}/interproscan-${major_version}-${minor_version}-64-bit.tar.gz
wget https://github.com/sib-swiss/pftools3/archive/refs/tags/v${pftools_version}.tar.gz
md5sum -c interproscan-${major_version}-${minor_version}-64-bit.tar.gz.md5
tar xvzf interproscan-${major_version}-${minor_version}-64-bit.tar.gz
tar xzxf v${pftools_version}.tar.gz

#replace the data folders in the conda environment with the new ones you downloaded
rm -rf ${HOME}/.conda/envs/interproscan/share/InterProScan/data/
cp -r interproscan-${major_version}-${minor_version}/data ${HOME}/.conda/envs/interproscan/share/InterProScan/

#compile pftools and move the binaries you need to the conda bin
mkdir pftools3-3.2.10/build
cd pftools3-3.2.10/build
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/opt/interproscan/prosite/ -DCMAKE_BUILD_TYPE=Release -DUSE_GRAPHICS=OFF -DUSE_PDF=OFF -DUSE_AFFINITY=OFF
make
make test
rm ${HOME}/.conda/envs/interproscan/share/InterProScan/bin/prosite/pfscanV3 ${HOME}/.conda/envs/interproscan/share/InterProScan/bin/prosite/pfsearchV3
cp src/C/pfscanV3 ${HOME}/.conda/envs/interproscan/share/InterProScan/bin/prosite/
cp src/C/pfsearchV3 ${HOME}/.conda/envs/interproscan/share/InterProScan/bin/prosite/
cd ../..

#Fix the sfld and superfamily hmm libraries as per the instructions of @pmjklemm (with minor tweak to include path)
data_dir=${HOME}/.conda/envs/interproscan/share/InterProScan
for f in ${data_dir}/data/sfld/*/sfld.hmm ${data_dir}/data/superfamily/*/hmmlib_*[0-9]; do
cp $f $f.bak;
perl -lne '$_=~s/[\s\n]+$//g;if(/^(NAME|ACC) +(.*)$/){if(exists $d{$2}){$d{$2}+=1;$_.="-$d{$2}"}else{$d{$2}=0;}}print "$_"' $f > $f.tmp; mv $f.tmp $f;
done

#go into the interproscan.properties file located in ${HOME}/.conda/envs/interproscan/share/InterProScan and make the following changes
#binary.prosite.psscan.pl.path=ps_scan.pl --> binary.prosite.psscan.pl.path=${bin.directory}/prosite/ps_scan.pl
#binary.prosite.pfscanv3.path=pfscanV3 --> binary.prosite.pfscanv3.path=${bin.directory}/prosite/pfscanV3
#binary.prosite.pfsearchv3.path=pfsearchV3 --> binary.prosite.pfsearchv3.path=${bin.directory}/prosite/pfsearchV3
#binary.pfscanv3.path=pfscanV3 --> binary.pfscanv3.path=${bin.directory}/prosite/pfscanV3
#binary.pfsearchv3.path=pfsearchV3 --> binary.pfsearchv3.path=${bin.directory}/prosite/pfsearchV3

#and HOPEFULLY it works! I was able to run interproscan on the test data without any errors.
test_data=${HOME}/.conda/envs/interproscan/share/InterProScan/test_all_appl.fasta
interproscan.sh -i ${test_data} -f tsv -dp


#I was able to get database matches for every analysis except Antifam and PIRSR. I'm unsure if this is the expected output since the readthedocs site isn't clear on what we should get from the test run https://interproscan-docs.readthedocs.io/en/latest/HowToRun.html#interproscan-test-run
awk '{print $4}' test_all_appl.fasta.tsv | sort | uniq -c
      3 CDD
      2 Coils
     12 Gene3D
      2 Hamap
     13 MobiDBLite
     12 PANTHER
      3 PIRSF
     11 PRINTS
     12 Pfam
      5 ProSitePatterns
      2 ProSiteProfiles
      1 SFLD
      4 SMART
      6 SUPERFAMILY
      3 TIGRFAM

Hope this helps someone out there!

**Comment by YuLanSky** [comment]
It work for me.
