### ISSUE TITLE
Java 9.0

### ISSUE THREAD

**Issue by jjkoehorst** [ebi-pf-team/interproscan#47]
The message is pretty clear that InterProScan cannot run on 1.9 but do you know when it will?

> Java version 1.8 is required to run InterProScan.
>     Detected version 9.0
>     Please install the correct version.

**Comment by gsn7** [comment]
Java 10 is scheduled for release this year, so we will unlikely upgrade to support Java 9

**Comment by mifraser** [comment]
As Java 10 is only supported for a limited time there is no plan for that. We'll be looking to upgrade InterProScan to work with Java 11 which is the next long-term-support release of Java. But since Java 11 only just came out we'll need some time to look at the details before we have a better idea when it would fit into the release schedule.
